import { normalizeHoldings } from "./portfolioSchema.js";

export function tuckerDemoHoldings() {
  return normalizeHoldings([
    {
      ticker: "UPRO",
      name: "ProShares UltraPro S&P 500",
      account: "Taxable Brokerage",
      accountType: "Taxable",
      shares: 180,
      price: 78.4,
      costBasis: 10980,
      dailyChange: -510,
      targetWeight: 0.08,
      sector: "Broad market",
      assetClass: "ETF",
      strategySleeve: "Leveraged growth",
      thesisStatus: "Active",
      riskLevel: "Very high",
      dividendYield: 0.006,
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "High-octane S&P exposure for long-term risk-on compounding, reviewed frequently due to leverage decay."
    },
    {
      ticker: "VGT",
      name: "Vanguard Information Technology ETF",
      account: "Roth IRA",
      accountType: "Retirement",
      shares: 42,
      price: 612.3,
      costBasis: 20340,
      dailyChange: 220,
      targetWeight: 0.18,
      sector: "Mega-cap tech",
      assetClass: "ETF",
      strategySleeve: "Core index",
      thesisStatus: "Active",
      riskLevel: "Medium-high",
      dividendYield: 0.006,
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Core technology compounder with mega-cap quality exposure."
    },
    {
      ticker: "MU",
      name: "Micron Technology",
      account: "Taxable Brokerage",
      accountType: "Taxable",
      shares: 95,
      price: 132.1,
      costBasis: 8725,
      dailyChange: 780,
      targetWeight: 0.08,
      sector: "Semiconductors",
      assetClass: "Equity",
      strategySleeve: "AI / semiconductor",
      thesisStatus: "Needs review",
      riskLevel: "High",
      quant: 4.43,
      valuationGrade: "B",
      growthGrade: "A-",
      profitabilityGrade: "B+",
      momentumGrade: "A",
      revisionsGrade: "A-",
      nextEarnings: "2026-06-26",
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Memory cycle leverage and AI server demand, but earnings cyclicality needs review."
    },
    {
      ticker: "SOXL",
      name: "Direxion Daily Semiconductor Bull 3X Shares",
      account: "Roth IRA",
      accountType: "Retirement",
      shares: 210,
      price: 52.8,
      costBasis: 8400,
      dailyChange: -1180,
      targetWeight: 0.05,
      sector: "Semiconductors",
      assetClass: "ETF",
      strategySleeve: "Leveraged growth",
      thesisStatus: "Active",
      riskLevel: "Very high",
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Leveraged semiconductor momentum sleeve; should stay capped and actively monitored."
    },
    {
      ticker: "CRDO",
      name: "Credo Technology Group",
      account: "Taxable Brokerage",
      accountType: "Taxable",
      shares: 260,
      price: 64.2,
      costBasis: 11960,
      dailyChange: 950,
      targetWeight: 0.06,
      sector: "Semiconductors",
      assetClass: "Equity",
      strategySleeve: "Speculative",
      thesisStatus: "Missing thesis",
      riskLevel: "High",
      quant: 4.12,
      valuationGrade: "D+",
      growthGrade: "A",
      profitabilityGrade: "C+",
      momentumGrade: "A",
      revisionsGrade: "B",
      nextEarnings: "2026-06-02",
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: ""
    },
    {
      ticker: "NVDA",
      name: "NVIDIA",
      account: "HSA",
      accountType: "HSA",
      shares: 18,
      price: 1014,
      costBasis: 12366,
      dailyChange: 610,
      targetWeight: 0.12,
      sector: "Semiconductors",
      assetClass: "Equity",
      strategySleeve: "AI / semiconductor",
      thesisStatus: "Active",
      riskLevel: "High",
      quant: 4.92,
      valuationGrade: "C",
      growthGrade: "A+",
      profitabilityGrade: "A+",
      momentumGrade: "A",
      revisionsGrade: "A+",
      nextEarnings: "2026-05-28",
      dividendYield: 0.0003,
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "AI infrastructure leader; keep sizing disciplined because it drives portfolio concentration."
    },
    {
      ticker: "AMD",
      name: "Advanced Micro Devices",
      account: "Traditional IRA",
      accountType: "Retirement",
      shares: 70,
      price: 164.5,
      costBasis: 10570,
      dailyChange: -180,
      targetWeight: 0.07,
      sector: "Semiconductors",
      assetClass: "Equity",
      strategySleeve: "AI / semiconductor",
      thesisStatus: "Active",
      riskLevel: "High",
      quant: 3.78,
      valuationGrade: "C-",
      growthGrade: "B+",
      profitabilityGrade: "B",
      momentumGrade: "B",
      revisionsGrade: "C",
      nextEarnings: "2026-07-29",
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "AI accelerator challenger; watch revision trend and margin proof."
    },
    {
      ticker: "QQQ",
      name: "Invesco QQQ Trust",
      account: "Traditional IRA",
      accountType: "Retirement",
      shares: 36,
      price: 472.9,
      costBasis: 14220,
      dailyChange: 95,
      targetWeight: 0.1,
      sector: "Mega-cap tech",
      assetClass: "ETF",
      strategySleeve: "Core index",
      thesisStatus: "Active",
      riskLevel: "Medium-high",
      dividendYield: 0.006,
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Nasdaq core exposure; overlaps heavily with VGT and top AI names."
    },
    {
      ticker: "SGOV",
      name: "iShares 0-3 Month Treasury Bond ETF",
      account: "Taxable Brokerage",
      accountType: "Taxable",
      shares: 85,
      price: 100.42,
      costBasis: 8510,
      dailyChange: 4,
      targetWeight: 0.08,
      sector: "Treasuries",
      assetClass: "Treasuries",
      strategySleeve: "Treasuries / hedge",
      thesisStatus: "Active",
      riskLevel: "Low",
      dividendYield: 0.052,
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Dry powder and volatility ballast."
    },
    {
      ticker: "CASH",
      name: "Core cash position",
      account: "Taxable Brokerage",
      accountType: "Taxable",
      shares: 1,
      price: 6420,
      marketValue: 6420,
      costBasis: 6420,
      dailyChange: 0,
      targetWeight: 0.06,
      sector: "Cash",
      assetClass: "Cash",
      strategySleeve: "Cash",
      thesisStatus: "Active",
      riskLevel: "Low",
      source: "demo-fidelity",
      sourceAsOf: "2026-05-21",
      thesis: "Liquidity for opportunity buys and near-term flexibility."
    }
  ]);
}
